apiVersion: apps/v1
kind: Deployment
metadata:
  name: bugs-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bugs
  template:
    metadata:
      labels:
        app: bugs
    spec:
      containers:
        - name: bugs
          # image: us.gcr.io/ticketing-dev-289619/bugs
          image: danieldotinc/bugs
          # resources:
          #   limits:
          #     memory: '128Mi'
          #     cpu: '500m'
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: JWT_KEY
              value: 'asdf'
            # - name: JWT_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: jwt-secret
            #       key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: bugs-srv
spec:
  selector:
    app: bugs
  ports:
    - name: bugs
      protocol: TCP
      port: 3000
      targetPort: 3000
